---
- name: restart apache
  systemd:
    name: apache2
    state: restarted

- name: restart sshd
  systemd:
    name: 'ssh.service'
    state: restarted

- name: restart WebSSO daemon
  systemd: daemon_reload=yes name=websso-daemon state=restarted enabled=yes
