---
- name: restart filebeat
  service:  name=filebeat state=restarted
  when: use_logserver
  listen: "restart filebeat"

- name: restart rsyslog
  service:  name=rsyslog state=restarted
  listen: "restart rsyslog"

- name: restart LDAP
  service:  name=slapd state=restarted enabled=yes
  listen: "restart slapd"

- name: systemd daemon-reload
  systemd: daemon_reload=yes

