---
ldap_dir: "/etc/ldap"
ldap_ldif_dir: "{{ ldap_dir }}/schema"
ldap_certs_dir: "{{ ldap_dir }}/certs"
ldap_backup_dir: "{{backup_base}}/ldap"

ldap_user: openldap
ldap_group: openldap

ldap_loglevel: "stats"
