---
sbs_openidc_timeout: 86400

sbs_repository: https://github.com/SURFscz/SBS.git
sbs_version: main

sbs_work_dir: "/opt/sbs"
sbs_git_dir: "{{ sbs_work_dir }}/sbs"
sbs_env_dir: "{{ sbs_work_dir }}/sbs-env"

sbs_db_name: "sbs"
sbs_db_user: "sbs"
sbs_db_host: "localhost"

sbs_mail_host: "{{ mail.relay_to }}"
sbs_mail_port: "{{ mail.relay_port }}"

sbs_oidc_crypto_password: "CHANGEME"
sbs_uid_attribute: "sub"

sbs_disclaimer_color: "#a29c13"
sbs_disclaimer_label: wsgi

sbs_urn_namespace: "urn:example:sbs"
sbs_restricted_co_default_org: "example.org"

sbs_mail_sender_name: "SURF"
sbs_mail_sender_email: "no-reply@surf.nl"
sbs_exceptions_mail: root@localhost

sbs_wiki_link: "https://www.example.org/wiki"

sbs_backend_port: 80

sbs_cron_hour_of_day: 4
sbs_seed_allowed: False
sbs_api_keys_enabled: True
sbs_feedback_enabled: True
sbs_audit_trail_notifications_enabled: True
sbs_send_exceptions: False
sbs_send_js_exceptions: False
sbs_open_notifications_enabled: True

sbs_oidc_config_url: "http://localhost/.well-known/openid-configuration"
sbs_oidc_authz_endpoint: "http://localhost/OIDC/authorization"
sbs_oidc_token_endpoint: "http://localhost/OIDC/token"
sbs_oidc_userinfo_endpoint: "http://localhost/OIDC/userinfo"
