---
- name: Create new SP test root index.php
  template:
    src: sp_index.php.j2
    dest: /var/www/html/index.php
    mode: 0644

- name: Add websites
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item }}.conf"
    mode: 0644
  with_items:
    - sp

- name: Enable websites
  file:
    src: "/etc/apache2/sites-available/{{ item }}.conf"
    dest: "/etc/apache2/sites-enabled/00-{{ item }}.conf"
    state: link
  with_items:
    - sp

- name: Listen to SP port
  blockinfile:
    path: "/etc/apache2/ports.conf"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ hostnames.sp }}"
    block: |
      Listen {{ sp_test_port }}

- name: SimpleSaml {{ environment_string }} metadata
  template:
    src: "{{ item }}.j2"
    dest: "{{ simplesaml_project_dir }}/simplesaml/metadata/{{ item }}"
    owner: "www-data"
  with_items:
    - saml20-idp-remote.php
