---
testidp_name: "sram-testidp"
testidp_user: "sram-testidp"
testidp_group: "sram-testidp"
testidp_dir: "/opt/{{testidp_name}}"
testidp_html_dir: "{{testidp_dir}}/html"
testidp_ip_allow: ["all"]
testidp_hostname: "test-idp.sram.surf.nl"
testidp2_hostname: "test-idp-2.sram.surf.nl"

testidp_employee_passwd: "employee"
testidp_student_passwd: "student"
testidp_orgAdmin_passwd: "orgAdmin"
testidp_orgManager_passwd: "orgManager"
testidp_unitManager_passwd: "unitManager"
testidp_serviceAdmin_passwd: "serviceAdmin"
testidp_serviceManager_passwd: "serviceManager"
testidp_coAdmin_passwd: "coAdmin"
testidp_normalUser_passwd: "normalUser"
testidp_extra_users: []
