---
domain: "{{base_domain}}"

sp_protocol: "{{http_proto}}://"
sp_hostname: "comanage.{{ domain }}"
sp_home: "/registry"

# Default values for the self-signed certificate are based on the certificate hostname
sp_technical_contact_gn: "John"
sp_technical_contact_sn: "Doe"
sp_technical_contact: "ict@{{ domain }}"
sp_organisation: "example Ltd."
sp_organisation_url: "https://www.example.com"

comanage_port: 80
comanage_repo_url: "https://github.com/SURFscz/comanage-registry.git"
comanage_repo_version: "scz"
comanage_db_user: comanage
comanage_db: registry
comanage_www_user: "www-data"
comanage_admin_given_name: "{{admin.fn}}"
comanage_admin_family_name: "{{admin.sn}}"
comanage_admin_username: "{{admin.eppn}}"
comanage_email_from: "no-reply@{{domain}}"
comanage_templatemanager_scripts: "/opt/scz/scripts"

comanage_full_hostname: "{{ sp_hostname }}"

comanage_scope: "{{base_domain}}"

idp_mellon_path: /etc/apache2/mellon/satosa
idp_metadata_url: "https://proxy.{{base_domain}}/md/SamlIdP.xml"
idp_extract_certificate: True
