---
# SimpleSAMLphp
simplesaml_version: "2.4.4"


simplesaml_download_url: "https://github.com/simplesamlphp/simplesamlphp/releases/download/\
                          v{{ simplesaml_version }}/\
                          simplesamlphp-{{ simplesaml_version }}-full.tar.gz"
simplesaml_checksum: "sha256:7a6811960cfc49e18f8cd7b309b016dbcb8c4ce1559e31482705fd8342b9eb16"

simplesaml_name: "ssp"
simplesaml_user: "ssp-user"
simplesaml_group: "ssp-group"
simplesaml_project_dir: "/opt/{{simplesaml_name}}"
simplesaml_tmp_dir: "{{simplesaml_project_dir}}/tmp/"
simplesaml_cert_dir: "{{simplesaml_project_dir}}/cert/"
