---
# SimpleSAMLphp
simplesaml_version: "2.4.4"


simplesaml_download_url: "https://github.com/simplesamlphp/simplesamlphp/releases/download/\
                          v{{ simplesaml_version }}/\
                          simplesamlphp-{{ simplesaml_version }}-full.tar.gz"
simplesaml_checksum: "sha256:01e198e67f32b4bbf8946740a93737e790b7d113da425e05146f2ee80ab24f32"

simplesaml_name: "ssp"
simplesaml_user: "ssp-user"
simplesaml_group: "ssp-group"
simplesaml_project_dir: "/opt/{{simplesaml_name}}"
simplesaml_tmp_dir: "{{simplesaml_project_dir}}/tmp/"
simplesaml_cert_dir: "{{simplesaml_project_dir}}/cert/"
